### ISSUE TITLE
Configuração focada para PWA

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/react-app-boilerplate#6]
Eu não entendi bem se já ta tudo pronto para funcionar a configuração do PWA, mas caso tenha que criar alguma facilitação na configuração, aqui tem uma issue para isso.

**Comment by vilaboim** [comment]
Imagino que tenha as configs básicas, como na Vue-cli.

**Comment by stanleygomes** [comment]
Ótimo!!
