### ISSUE TITLE
Port da aplicação para electron

### ISSUE THREAD

**Issue by stanleygomes** [SoftboxLab/react-app-boilerplate#8]
Vocês acham válido?

https://getstream.io/blog/takeaways-on-building-a-react-based-app-with-electron

**Comment by vilaboim** [comment]
Por enquanto não, não existe demanda e ainda nem sabemos a estrutura para um projeto web.
Acho importante dominarmos a estrutura de um projeto React web antes de adicionar mais coisas.

**Comment by rafael1995** [comment]
Também acho que não por não termos tanta demanda para aplicações desktop, sem falar da crescente com o pwa

**Comment by stanleygomes** [comment]
Beleza.

Vou fechar essa issue e trabalhar em outra ideia.
